services:
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - /volumes/minio:/data
    ports:
      - "9222:9000"
      - "9223:9001"
    command: [ "server", "--console-address", ":9001", "/data" ]

  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /volumes/postgres_data:/var/lib/postgresql/data